INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	1	, 'First Comment', '2020-12-01', 1 , 1);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	2	, 'Second Comment', '2020-12-02', 1 , 2);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	3	, 'Third Comment', '2020-12-03', 2 , 3);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	4	, 'Fourth Comment', '2020-12-04', 3 , 3);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	5	, 'Fiveth Comment', '2020-12-05', 4 , 5);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	6	, 'Sixth Comment','2020-12-06' , 5 , 4);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	7	, 'Seventh Comment', '2020-12-07', 6 , 4);