INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	1	, 'First Comment', now(), 1 , 1);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	2	, 'Second Comment', now(), 1 , 2);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	3	, 'Third Comment', now(), 2 , 3);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	4	, 'Fourth Comment', now(), 3 , 3);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	5	, 'Fiveth Comment', now(), 4 , 5);
INSERT INTO public.PRODUCTCOMMENT( ID, COMMENT, COMMENT_DATE, ID_PRODUCT, ID_USER) VALUES (	6	, 'Fourth Comment', now(), 5 , 4);